#------------------------------------------------------------------------------
# usage: configure tutor SMTP email service
#------------------------------------------------------------------------------
name: Open edX Tutor k8s configure Redis service
description: Github Action to use Tutor to configure a remote Redis service for use with Open edX running on AWS EKS Kubernetes
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namesapce to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    # retrieve the Redis connection parameter that we created in Terraform:
    #   REDIS_HOST: redis.app.yourschool.edu
    #
    # see: https://github.com/Medality-Health/openedx_devops/blob/main/terraform/modules/redis/main.tf
    - name: fetch Redis configuration from k8s
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: redis

    - name: set other environment variables
      shell: bash
      run: |-
        echo "TUTOR_RUN_REDIS=false" >> $GITHUB_ENV

    - name: save config
      shell: bash
      run: tutor config save
